# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSLSTMCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  block_channels: [24, 24, 24, 24]
  hidden_size: 128  # LSTM hidden state size
  mlp_features: [384]

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  
  padding: [1800, 200]  # 900ms past context, 100ms future context